package com.aprendiendoandroidstudio.recyclerviewuno

class AnimalProvider {
    companion object{
        val animalList = listOf(
            Animal(
                "Oveja",
                "Vertebrado",
                "Herbívoro",
                "Terrestre",
                "Vivíparo",
                "https://s1.significados.com/foto/animal-herbivoro-ovino-oveja.jpg?class=article"
            ),
            Animal(
                "León",
                "Vertebrado",
                "Carnivoro",
                "Terrestre",
                "Viviparo",
                "https://s1.significados.com/foto/leon-como-animal-carnivoro.jpg?class=article"
            ),
            Animal(
                "Hipopótamo",
                "Vertebrado",
                "Insectívoro",
                "Semiacuático",
                "viviparos",
                "https://s1.significados.com/foto/hippopotamus-1170205-1920.jpg?class=article"
            ),
            Animal(
                "Iguana",
                "Vertebrado",
                "Hervívoro",
                "Terrestre",
                "Ovíparo",
                "https://s1.significados.com/foto/iguana-854332-1920.jpg?class=article"
            ),
            Animal(
                "Águila",
                "Vertebrado",
                "Carnívoras y Carroñeras",
                "Aéreo",
                "Ovíparo",
                "https://s1.significados.com/foto/a-guila.jpg?class=article"
            ),
            Animal(
                "Oveja",
                "Vertebrado",
                "Herbívoro",
                "Terrestre",
                "Vivíparo",
                "https://s1.significados.com/foto/animal-herbivoro-ovino-oveja.jpg?class=article"
            ),
            Animal(
                "León",
                "Vertebrado",
                "Carnivoro",
                "Terrestre",
                "Viviparo",
                "https://s1.significados.com/foto/leon-como-animal-carnivoro.jpg?class=article"
            ),
            Animal(
                "Hipopótamo",
                "Vertebrado",
                "Insectívoro",
                "Semiacuático",
                "viviparos",
                "https://s1.significados.com/foto/hippopotamus-1170205-1920.jpg?class=article"
            ),
            Animal(
                "Iguana",
                "Vertebrado",
                "Hervívoro",
                "Terrestre",
                "Ovíparo",
                "https://s1.significados.com/foto/iguana-854332-1920.jpg?class=article"
            ),
            Animal(
                "Águila",
                "Vertebrado",
                "Carnívoras y Carroñeras",
                "Aéreo",
                "Ovíparo",
                "https://s1.significados.com/foto/a-guila.jpg?class=article"
            )
        )
    }
}